baseURL = "https://seita.icu/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "Seita"
theme = "hugo-notepadium"
copyright = "Â©2021 Seita Uchimura."
hasCJKLanguage = true
enableRobotsTXT = true
# Enable Disqus
# disqusShortname = "seita-blog"
enableEmoji = true

# Google Analytics
#googleAnalytics = "UA-123-45"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "dark"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
logo = ""  # if you have a logo png
og_image = "img/me.png"
slogan = "You ain't gonna need it"
license = ""  # CC License
fullRss = false # Puts entire HTML post into rss 'description' tag. If unset, default is false.
ogpApiEndpoint = "https://kotsukotsu-ogp-api.vercel.app/api/ogp?url="

[params.assets]
css = ["css/custom.css", "css/blogcard.css"]  # *.css/scss/sass

[params.comments]
enable = true  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "xcode"
darkTheme = "xcode-dark"  # apply this theme in dark mode

[params.share]
enable = false
addThisId = ""
inlineToolId = ""

#[params.nav]
#showCategories = true
#showTags = true
[[params.nav.custom]]
title = "Articles"
url = "/"

[[params.nav.custom]]
title = "About"
url = "/about"

[[params.nav.custom]]
title = "Categories"
url = "/categories"

[[params.nav.custom]]
title = "Tags"
url = "/tags"

[params.profile]
enable = true
avatar = "/img/me.png"
name = "Seita Uchimura"
bio = "Software Engineer in Tokyo"  # support markdown syntax
twitter = "sei_uchi_mura"  # https://twitter.com/XXX
github = "seita-uc"  # https://github.com/XXX
